# Generated by Django 4.0.2 on 2022-02-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company_dete'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='data'),
        ),
    ]
