# Generated by Django 4.0.2 on 2022-02-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='fileCSV'),
        ),
    ]
