# Generated by Django 4.0.2 on 2022-02-07 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_company_file_alter_company_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'verbose_name': 'ORG File',
                'verbose_name_plural': 'ORG File',
                'db_table': 'company_csv',
                'ordering': ('id',),
            },
        ),
    ]
