# Generated by Django 4.0.2 on 2022-02-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_company_file_company_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
