# Generated by Django 4.0.2 on 2022-04-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_company_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'IP Address List',
                'verbose_name_plural': 'IP Address Table',
                'db_table': 'address_list',
            },
        ),
        migrations.CreateModel(
            name='capadailylog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Capa Daily Log List',
                'verbose_name_plural': 'Capa Daily Log Table',
                'db_table': 'capa_daily_log',
            },
        ),
        migrations.CreateModel(
            name='company_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Contact List',
                'verbose_name_plural': 'Contact Table',
                'db_table': 'company_contact',
            },
        ),
        migrations.CreateModel(
            name='company_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_th', models.CharField(blank=True, max_length=100, null=True)),
                ('initials', models.CharField(blank=True, max_length=100, null=True)),
                ('join_date', models.DateField(auto_now_add=True, null=True)),
                ('service_provider', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Company List',
                'verbose_name_plural': 'Company Table',
                'db_table': 'company_list',
            },
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company_list')),
            ],
            options={
                'verbose_name': 'Device List',
                'verbose_name_plural': 'Device Table',
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='device_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Device Type List',
                'verbose_name_plural': 'Device Type Table',
                'db_table': 'device_type',
            },
        ),
        migrations.CreateModel(
            name='file_csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='File csv')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File CSV List',
                'verbose_name_plural': 'File CSV Table',
                'db_table': 'file_csv',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='file_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='report')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File Report List',
                'verbose_name_plural': 'File Report Table',
                'db_table': 'file_report',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('src_address', models.CharField(blank=True, max_length=100, null=True)),
                ('des_address', models.CharField(blank=True, max_length=100, null=True)),
                ('src_user', models.CharField(blank=True, max_length=100, null=True)),
                ('des_user', models.CharField(blank=True, max_length=100, null=True)),
                ('protocol', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('last_datetime', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('file_path', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('malware_name', models.CharField(blank=True, max_length=100, null=True)),
                ('src_geolocation', models.CharField(blank=True, max_length=100, null=True)),
                ('des_geolocation', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company_list')),
            ],
            options={
                'verbose_name': 'Trend List',
                'verbose_name_plural': 'Trend Table',
                'db_table': 'trend',
            },
        ),
        migrations.AlterModelOptions(
            name='vulnerability',
            options={'verbose_name': 'Vulnerability List', 'verbose_name_plural': 'Vulnerability Table'},
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='Name',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='BID',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='CANVAS',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='CVE',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='CVSS_v2_0_Base_Score',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='CVSS_v2_0_Temporal_Score',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='CVSS_v3_0_Base_Score',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='CVSS_v3_0_Temporal_Score',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Core_Impact',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Host',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='MSKB',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Metasploit',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Plugin_ID',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Plugin_Modification_Date',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Plugin_Output',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Plugin_Publication_Date',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Port',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Protocol',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Risk',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Risk_Factor',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='STIG_Severity',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='See_Also',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Solution',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='Synopsis',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='XREF',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='analysis_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='analysis_th',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='detail_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='detail_th',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='effect_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='effect_th',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='name_th',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='priority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='solution_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='solution_th',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='vulnerability',
            table='vulnerability',
        ),
        migrations.DeleteModel(
            name='company',
        ),
        migrations.DeleteModel(
            name='company_csv',
        ),
        migrations.AddField(
            model_name='device',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device_type'),
        ),
        migrations.AddField(
            model_name='company_contact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company_list'),
        ),
        migrations.AddField(
            model_name='capadailylog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company_list'),
        ),
        migrations.AddField(
            model_name='address_list',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company_list'),
        ),
    ]
