# Generated by Django 4.0.2 on 2022-03-22 04:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_company_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='file',
            field=models.FileField(upload_to=api.models.file_path),
        ),
        migrations.AlterField(
            model_name='company_csv',
            name='file',
            field=models.FileField(upload_to=api.models.file_path),
        ),
    ]
