# Generated by Django 4.0.2 on 2022-03-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_company_type_alter_company_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='dete',
            new_name='date',
        ),
    ]
