# Generated by Django 4.0.2 on 2022-04-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_address_list_capadailylog_company_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_report',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
