# Generated by Django 4.0.2 on 2022-04-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_file_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_csv',
            name='file',
            field=models.FileField(upload_to='file'),
        ),
    ]
