# Generated by Django 4.0.2 on 2022-04-07 10:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_file_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_csv',
            name='file',
            field=models.FileField(upload_to=api.models.file_path),
        ),
        migrations.AlterField(
            model_name='file_report',
            name='file',
            field=models.FileField(upload_to=api.models.file_path),
        ),
    ]
