# Generated by Django 4.0.2 on 2022-04-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_file_csv_file_alter_file_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_report',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
